#!/usr/bin/env bash
# script to display info about our subdomains

sub_domain_info() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        other_sub=("www" "lb-01" "web-01" "web-02")

        for sub in "${other_sub[@]}"; do
            final_path="$sub.$domain"
            record_type=$(dig $final_path | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
            ip_address=$(dig $final_path | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
            echo The subdomain $sub is a $record_type record and points to $ip_address
        done
    else
        final_path="$subdomain.$domain"
        record_type=$(dig $final_path | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
        ip_address=$(dig $final_path | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
        echo The subdomain $subdomain is a $record_type record and points to $ip_address
    fi
}


sub_domain_info "$1" "$2"
