#!/usr/bin/env bash
# script that transfers a file from our client to a server

command="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

# getting our args
file_path="$1"
server="$2"
username="$3"
ssh_path="$4"

if [ "$4" ]; then
   scp -i "$ssh_path" -o StrictHostKeyChecking=no "$file_path" "$username@$server:~"
elif [ "$3" ]; then
     scp -o StrictHostKeyChecking=no "$file_path" "$username@$server~"
else
	echo "$command";
fi