#!/usr/bin/env bash
# script to configure nginx

event{


}

http {

    server {
        server_name nginx-handbook.test;

        location / {
            return 200 "Hello world!";
        }
    }
}