#!/usr/bin/env bash
# script to install and configure nginx

sudo apt update 
sudo apt upgrade -y
sudo apt install nginx -y

touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

echo "events {


}

http {
        server {
                listen 80;
                server_name stanceray.tech;
                root /var/www/html;
                index index.html;
        }
}" > /etc/nginx/nginx.conf

sudo service nginx restart
