#!/usr/bin/env bash
# Script to handle url redirection

sudo apt update -y
sudo apt upgrade
sudo install nginx -y


echo "events {


}

http {
        server {
                listen 80;
                server_name stanceray.tech;
                root /etc/nginx//html;
                index index.html;

                location /redirect_me {
                        return 301 https://stanceray.com;
                }
        }
}" > /etc/nginx/sites-enabled

sudo service nginx restart
