#!/usr/bin/env bash
# script to redirect a url

event{


}

http {
    server {
        server_name stanceray.tech;

        location / {
            return 200 "Hello world!";
        }
        location /redirect_me {
            return 301 https://stanceray.com;
        }
    }

}