#!/usr/bin/env bash
# script for a page that isn't found

sudo apt update 
sudo apt upgrade -y
sudo apt install nginx -y

touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html


echo "events {


}

http {
        server {
                listen 80;
                server_name stanceray.tech;
                root /var/www/html;
                index index.html;

                location /redirect_me {
                        return 301 https://stanceray.com;
                }
                
                error_page 404 /404.html;
                location = /404.html {
                        root /var/www/html;
                        internal;
                }
        }
}" > /etc/nginx/nginx.conf

sudo service nginx restart
