#!/usr/bin/env bash
#displays "To infinity and beyond" indefinitely
#displays I am invincible!!! when receiving a SIGTERM signal
trap "echo 'I am invincible!!!'" 15


# print the message forever
while true;
do
	echo "To infinity and beyond";
	sleep 2
done
